/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'id' : UserID,
  'username' : string,
  'coinBalance' : number,
  'phone' : string,
}
export interface Task {
  'id' : string,
  'status' : string,
  'title' : string,
  'creatorId' : string,
  'rewardCoins' : bigint,
  'description' : string,
  'claimedBy' : [] | [string],
  'timestamp' : [] | [bigint],
}
export interface TopUpRequest {
  'id' : string,
  'status' : string,
  'realAmount' : number,
  'verificationNote' : string,
  'userId' : string,
  'timestamp' : [] | [bigint],
  'coinsRequested' : bigint,
}
export interface Transaction {
  'id' : string,
  'note' : string,
  'toUser' : string,
  'timestamp' : [] | [bigint],
  'fromUser' : string,
  'amount' : number,
  'purpose' : string,
}
export type UserID = string;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveTopUp' : ActorMethod<[string, string], undefined>,
  'adminGetAllMessages' : ActorMethod<[string], Array<Transaction>>,
  'adminGetAllTransactions' : ActorMethod<[string], Array<Transaction>>,
  'adminGetAllUsers' : ActorMethod<[string], Array<Profile>>,
  'adminGetTopUpRequests' : ActorMethod<[string], Array<TopUpRequest>>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminRejectTopUp' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimTask' : ActorMethod<[string], undefined>,
  'completeTask' : ActorMethod<[string], undefined>,
  'createTask' : ActorMethod<[string, string, bigint], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string], Array<Transaction>>,
  'getMyBalance' : ActorMethod<[], number>,
  'getMyMessages' : ActorMethod<[], Array<Transaction>>,
  'getMyTopUpRequests' : ActorMethod<[], Array<TopUpRequest>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string], UserID>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendCoins' : ActorMethod<[string, string, number, string, string], number>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'submitTopUpRequest' : ActorMethod<[number, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];