/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'note' : IDL.Text,
  'toUser' : IDL.Text,
  'timestamp' : IDL.Opt(IDL.Int),
  'fromUser' : IDL.Text,
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});
export const UserID = IDL.Text;
export const Profile = IDL.Record({
  'id' : UserID,
  'username' : IDL.Text,
  'coinBalance' : IDL.Float64,
  'phone' : IDL.Text,
});
export const TopUpRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'realAmount' : IDL.Float64,
  'verificationNote' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Opt(IDL.Int),
  'coinsRequested' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'creatorId' : IDL.Text,
  'rewardCoins' : IDL.Nat,
  'description' : IDL.Text,
  'claimedBy' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveTopUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminGetAllMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'adminGetAllTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'adminGetTopUpRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TopUpRequest)],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminRejectTopUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimTask' : IDL.Func([IDL.Text], [], []),
  'completeTask' : IDL.Func([IDL.Text], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getMyMessages' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserID], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendCoins' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Float64],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitTopUpRequest' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'note' : IDL.Text,
    'toUser' : IDL.Text,
    'timestamp' : IDL.Opt(IDL.Int),
    'fromUser' : IDL.Text,
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  const UserID = IDL.Text;
  const Profile = IDL.Record({
    'id' : UserID,
    'username' : IDL.Text,
    'coinBalance' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const TopUpRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'realAmount' : IDL.Float64,
    'verificationNote' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Opt(IDL.Int),
    'coinsRequested' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'creatorId' : IDL.Text,
    'rewardCoins' : IDL.Nat,
    'description' : IDL.Text,
    'claimedBy' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveTopUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminGetAllMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'adminGetAllTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'adminGetTopUpRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TopUpRequest)],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminRejectTopUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimTask' : IDL.Func([IDL.Text], [], []),
    'completeTask' : IDL.Func([IDL.Text], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getMyMessages' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserID], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendCoins' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Float64],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitTopUpRequest' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };